# Generated by Django 2.2.2 on 2019-07-16 21:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20190716_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
