# Generated by Django 2.2.2 on 2019-07-18 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20190716_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_item',
            field=models.CharField(error_messages={'required': 'It is required field'}, max_length=200),
        ),
    ]
